<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Sentinel.Contracts\Sentinel.Contracts.csproj" />
    <ProjectReference Include="..\Sentinel.Infrastructure\Sentinel.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="prometheus-net" Version="8.2.1" />
  </ItemGroup>
</Project>
